# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1453b38828cd29b1da90924ba5e91a514696dbdcd36b6f8d5636ed2e8ec608aa84875a4d5dbcfea5283e57a533f3795d998993fe3f2e4c96e5b235d67a267821

test:
  secret_key_base: 2ced7bc98ebaba22ad8537290075acbaee3aafb449f20af692cc997656641ec59c03b7e1329003048f8f5d83c1db910af701061a08db068cc5e27c1e7774a69e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
